### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by vychodlc** [andrea-claro/Hackintosh-Xiaomi-Air-13-2017#1]
can i know whether the efi is for xiaomi air 13.3 i3-8130U？

**Comment by andrea-claro** [comment]
It will eventually work. Initially the EFI has been taught for xiaomi mi air 13.3 2018 i5-8k, and then I've used it even for the xiaomi mi air 13.3 2017 i5-7k. 
The best way to know is trying...
